font-size=14
cursor-style=block
theme=gruvboxDarkHard
foreground=ffffff

keybind=super+shift+r=reload_config

keybind=shift+ctrl+h=new_split:left
keybind=shift+ctrl+j=new_split:down
keybind=shift+ctrl+k=new_split:up
keybind=shift+ctrl+l=new_split:right
